export const ACTION_ONE = 'ACTION_ONE';
export const CONT2_LOADING = 'CONT2_LOADING';
export const CONT2_LOADED = 'CONT2_LOADED';

export const SHOW_ALERT_MODAL = 'SHOW_ALERT_MODAL';
export const HIDE_ALERT_MODAL = 'HIDE_ALERT_MODAL';
