export const ACTION_ONE = 'ACTION_ONE';
export const CONT2_LOADING = 'CONT2_LOADING';
export const CONT2_LOADED = 'CONT2_LOADED';

export const SHOW_ALERT_MODAL = 'SHOW_ALERT_MODAL';
export const HIDE_ALERT_MODAL = 'HIDE_ALERT_MODAL';

export const LOADING_USERS = 'LOADING_USERS';
export const LOADED_USERS = 'LOADED_USERS';
export const LOAD_USERS = 'LOAD_USERS';
export const DELETE_USER = 'DELETE_USER';

export const LOADING_UPDATES = 'LOADING_UPDATES';
export const LOADED_UPDATES = 'LOADED_UPDATES';
export const LOAD_UPDATES = 'LOAD_UPDATES';
export const DELETE_UPDATE_START = 'DELETE_UPDATE_START';
export const DELETE_UPDATE_SUCCESS = 'DELETE_UPDATE_SUCCESS';
export const DELETE_UPDATE_FAILURE = 'DELETE_UPDATE_FAILURE';
export const CLEAR_LOADED_UPDATES = 'CLEAR_LOADED_UPDATES';
